const placeholderCover = "/images/projects/placeholder-cover.svg";
const placeholderLogo = "/images/projects/placeholder-logo.svg";

export const TECH_CATEGORIES = [
    {
        id: "frontend",
        label: "Frontend",
        color: "text-primary",
        borderColor: "border-primary/30",
        bgColor: "bg-primary/10",
        techs: [
            { name: "Next.js", level: 90, note: "App Router, SSR, RSC", icon: "/icons/showcase/nextjs.svg" },
            { name: "React", level: 90, note: "Hooks, Context, Suspense", icon: "/icons/showcase/reactjs.svg" },
            { name: "TypeScript", level: 85, note: "Strict mode, generics", icon: "/icons/showcase/typescript.svg" },
            { name: "JavaScript", level: 92, note: "ES6+, async patterns", icon: "/icons/showcase/javascript-light.svg" },
            { name: "Tailwind CSS", level: 95, note: "Utility-first, design systems", icon: "/icons/showcase/tailwind.svg" },
        ],
    },

    {
        id: "backend",
        label: "Backend",
        color: "text-accent",
        borderColor: "border-accent/30",
        bgColor: "bg-accent/10",
        techs: [
            { name: "Node.js", level: 90, note: "REST APIs, middleware", icon: "/icons/nodejs.svg" },
            { name: "PostgreSQL", level: 90, note: "Relational databases", icon: "/icons/postgresql.svg" },
            { name: "Drizzle ORM", level: 87, note: "Schema design, migrations", icon: "/icons/drizzle-orm.svg" },
            { name: "Better Auth", level: 82, note: "Authentication & sessions", icon: "/icons/better-auth_light.svg" },
            { name: "Prisma", level: 78, note: "ORM, schema modeling", icon: "/icons/prisma-svgrepo-com.svg", iconClassName: "invert" },
            { name: "Supabase", level: 84, note: "Backend services, auth, storage", icon: "/icons/supabase.svg" },
            { name: "TanStack", level: 88, note: "Query, Table, Router", icon: "/icons/tanstack.svg" },
            { name: "Firebase", level: 80, note: "BaaS, real-time DB, auth", icon: "/icons/firebase.svg" },
            { name: "Redis", level: 75, note: "Caching, pub/sub", icon: "/icons/redis.svg" },
        ],
    },

    {
        id: "devops",
        label: "DevOps & OS",
        color: "text-secondary",
        borderColor: "border-secondary/30",
        bgColor: "bg-secondary/10",
        techs: [
            { name: "Linux", level: 94, note: "Daily driver, Arch & Ubuntu", icon: "/icons/linux.svg" },
            { name: "Git", level: 90, note: "Branching, rebasing, CLI", icon: "/icons/git.svg" },
            { name: "Docker", level: 82, note: "Containers, compose", icon: "/icons/docker.svg" },
            { name: "Vercel", level: 86, note: "CI/CD, edge functions", icon: "/icons/vercel.svg", iconClassName: "invert" },
            { name: "Railway", level: 78, note: "Deployments, hosting", icon: "/icons/railway.svg", iconClassName: "invert" },
            { name: "Cloudflare", level: 82, note: "CDN, Workers, R2", icon: "/icons/cloudflare.svg" },
            { name: "Bash / Zsh", level: 90, note: "Scripting, dotfiles", icon: "/icons/shell-light.svg" },
        ],
    },

    {
        id: "devops",
        label: "DevOps & OS",
        color: "text-secondary",
        borderColor: "border-secondary/30",
        bgColor: "bg-secondary/10",
        techs: [
            { name: "Linux", level: 94, note: "Daily driver, Arch & Ubuntu", icon: "/icons/showcase/linux.svg" },
            { name: "Git", level: 90, note: "Branching, rebasing, CLI", icon: "/icons/showcase/git.svg" },
            { name: "Docker", level: 82, note: "Containers, compose", icon: "/icons/showcase/docker.svg" },
            { name: "Vercel", level: 86, note: "CI/CD, edge functions", icon: "/icons/showcase/vercel.svg" },
            { name: "Railway", level: 78, note: "Deployments, hosting", icon: "/icons/showcase/railway.svg" },
            { name: "Cloudflare", level: 82, note: "CDN, Workers, R2", icon: "/icons/showcase/cloudflare.svg" },
            { name: "Bash / Zsh", level: 90, note: "Scripting, dotfiles", icon: "/icons/showcase/shell-light.svg" },
        ],
    },
];

export const TOOLS = [
    { name: "Neovim", tag: "editor", color: "text-accent", icon: "/icons/neovim.svg" },
    { name: "VSCode", tag: "editor", color: "text-primary", icon: "/icons/vscode.svg" },
    { name: "Figma", tag: "ui/ux design", color: "text-primary", icon: "/icons/figma.svg" },
    { name: "Adobe Photoshop", tag: "photo editing", color: "text-accent", icon: "/icons/adobe-photoshop.svg" },
    { name: "Adobe Illustrator", tag: "vector design", color: "text-secondary", icon: "/icons/adobe-illustrator.svg" },
    { name: "Adobe", tag: "creative suite", color: "text-accent", icon: "/icons/adobe.svg" },
    { name: "GitHub", tag: "vcs", color: "text-foreground", icon: "/icons/github.svg", iconClassName: "invert" },
    { name: "Postman", tag: "api testing", color: "text-accent", icon: "/icons/postman.svg" },
    { name: "Neon.tech", tag: "database", color: "text-secondary", icon: "/icons/neon-tech.svg" },
    { name: "Obsidian", tag: "notes", color: "text-secondary", icon: "/icons/obsidian.svg" },
    { name: "Notion", tag: "notes", color: "text-accent", icon: "/icons/notion-light.svg" },
];

export const PROJECTS = [
    {
        title: "Mindful Companion",
        desc: "AI mental health chatbot with self-help tools, mood tracking, and guided interventions. Designed to feel calm and trustworthy — not clinical.",
        period: "2026",
        cover: "/images/projects/mindful-cover.jpg",
        logo: "/images/projects/mindful-logo.webp",
        dot: "bg-[#1D9E75]",
        iconColor: "text-[#0F6E56]",
        iconBg: "bg-[#E1F5EE]",
        fallbackIcon: "🧠",
        techs: ["Next.js", "PostgreSQL", "Drizzle ORM", "Supabase"],
        liveUrl: "https://mindful-companion-gamma.vercel.app",
        githubUrl: null,
    },
    {
        title: "Minstrel Website",
        desc: "Library of songs collected from Discord, featuring search and playback with a custom-built audio player. Pairs with the Minstrel Bot to form a full pipeline.",
        period: "2026",
        cover: placeholderCover,
        logo: placeholderLogo,
        dot: "bg-[#BA7517]",
        iconColor: "text-[#854F0B]",
        iconBg: "bg-[#FAEEDA]",
        fallbackIcon: "🎵",
        techs: ["React", "Tailwind CSS", "TanStack", "Drizzle ORM", "Neon DB"],
        liveUrl: "https://minstel-web-cnq.vercel.app/",
        githubUrl: "https://github.com/ABritex/minstel-web-cnq",
    },
    {
        title: "Minstrel Bot",
        desc: "Discord bot that collects, organizes, and serves songs from Discord servers directly into the Minstrel website — the data backbone of the whole system.",
        period: "2026",
        cover: placeholderCover,
        logo: placeholderLogo,
        dot: "bg-[#7F77DD]",
        iconColor: "text-[#534AB7]",
        iconBg: "bg-[#EEEDFE]",
        fallbackIcon: "🤖",
        techs: ["TypeScript", "Discord.js", "Drizzle ORM", "Neon DB"],
        liveUrl: null,
        githubUrl: "https://github.com/ABritex/minstrel-bot",
    },
    {
        title: "JNDM Sari-Sari Store (Web)",
        desc: "Full-featured convenience store management web app for clients to manage inventory, sales, and analytics.",
        period: "2025",
        cover: placeholderCover,
        logo: "/images/projects/jndm-logo.webp",
        dot: "bg-[#4F46E5]",
        iconColor: "text-[#4338CA]",
        iconBg: "bg-[#EEF2FF]",
        fallbackIcon: "🛒",
        techs: ["Next.js", "Firebase", "Tailwind CSS"],
        liveUrl: null,
        githubUrl: null,
        status: "postponed",
    },
    {
        title: "JNDM Sari-Sari Store (Mobile)",
        desc: "Tablet-based cashier app for sari-sari stores. Streamlines transactions, inventory tracking, and customer management.",
        period: "2025",
        cover: placeholderCover,
        logo: "/images/projects/jndm-logo.webp",
        dot: "bg-[#059669]",
        iconColor: "text-[#047857]",
        iconBg: "bg-[#D1FAE5]",
        fallbackIcon: "📱",
        techs: ["Flutter", "Firebase", "Provider"],
        liveUrl: null,
        githubUrl: null,
        status: "postponed",
    },
    {
        title: "The Empire (Web)",
        desc: "Multi-purpose business management platform for food court, restaurant, PC cafe, and boarding room operations.",
        period: "2024",
        cover: placeholderCover,
        logo: "/images/projects/empire-logo.png",
        dot: "bg-[#DC2626]",
        iconColor: "text-[#B91C1C]",
        iconBg: "bg-[#FEF2F2]",
        fallbackIcon: "🏢",
        techs: ["Next.js", "Firebase", "TypeScript"],
        liveUrl: null,
        githubUrl: null,
        status: "postponed",
    },
    {
        title: "The Empire (Mobile)",
        desc: "Android-only staff app for The Empire building operations. Enables staff to manage orders, track bookings, and handle day-to-day operations.",
        period: "2024",
        cover: placeholderCover,
        logo: "/images/projects/empire-logo.png",
        dot: "bg-[#7C3AED]",
        iconColor: "text-[#6D28D9]",
        iconBg: "bg-[#F3E8FF]",
        fallbackIcon: "📱",
        techs: ["Android Studio", "Jetpack Compose", "Firebase"],
        liveUrl: null,
        githubUrl: null,
    }
];
