const placeholderCover = "/images/projects/placeholder-cover.svg";
const placeholderLogo = "/images/projects/placeholder-logo.svg";

export const TECH_CATEGORIES = [
    {
        id: "frontend",
        label: "Frontend",
        color: "text-primary",
        borderColor: "border-primary/30",
        bgColor: "bg-primary/10",
        progressColor: "bg-primary",
        techs: [
            { name: "Next.js", level: "Expert", note: "App Router, SSR, RSC", icon: "/icons/nextjs.svg" },
            { name: "React", level: "Expert", note: "Hooks, Context, Suspense", icon: "/icons/reactjs.svg" },
            { name: "TypeScript", level: "Proficient", note: "Strict mode, generics", icon: "/icons/typescript.svg" },
            { name: "JavaScript", level: "Expert", note: "ES6+, async patterns", icon: "/icons/javascript-light.svg" },
            { name: "Tailwind CSS", level: "Expert", note: "Utility-first, design systems", icon: "/icons/tailwind.svg" },
        ],
    },

    {
        id: "backend",
        label: "Backend",
        color: "text-accent",
        borderColor: "border-accent/30",
        bgColor: "bg-accent/10",
        progressColor: "bg-accent",
        techs: [
            { name: "Node.js", level: "Expert", note: "REST APIs, middleware", icon: "/icons/nodejs.svg" },
            { name: "PostgreSQL", level: "Expert", note: "Relational databases", icon: "/icons/postgresql.svg" },
            { name: "Drizzle ORM", level: "Proficient", note: "Schema design, migrations", icon: "/icons/drizzle-orm.svg" },
            { name: "Better Auth", level: "Proficient", note: "Authentication & sessions", icon: "/icons/better-auth_light.svg" },
            { name: "Prisma", level: "Familiar", note: "ORM, schema modeling", icon: "/icons/prisma-svgrepo-com.svg", iconClassName: "invert" },
            { name: "Supabase", level: "Proficient", note: "Backend services, auth, storage", icon: "/icons/supabase.svg" },
            { name: "TanStack", level: "Proficient", note: "Query, Table, Router", icon: "/icons/tanstack.svg" },
            { name: "Firebase", level: "Proficient", note: "BaaS, real-time DB, auth", icon: "/icons/firebase.svg" },
            { name: "Redis", level: "Familiar", note: "Caching, pub/sub", icon: "/icons/redis.svg" },
        ],
    },

    {
        id: "devops",
        label: "DevOps & OS",
        color: "text-secondary",
        borderColor: "border-secondary/30",
        bgColor: "bg-secondary/10",
        techs: [
            { name: "Linux", level: "Expert", note: "Daily driver, Arch & Ubuntu", icon: "/icons/linux.svg" },
            { name: "Git", level: "Expert", note: "Branching, rebasing, CLI", icon: "/icons/git.svg" },
            { name: "Docker", level: "Proficient", note: "Containers, compose", icon: "/icons/docker.svg" },
            { name: "Vercel", level: "Proficient", note: "CI/CD, edge functions", icon: "/icons/vercel.svg", iconClassName: "invert" },
            { name: "Railway", level: "Familiar", note: "Deployments, hosting", icon: "/icons/railway.svg", iconClassName: "invert" },
            { name: "Cloudflare", level: "Proficient", note: "CDN, Workers, R2", icon: "/icons/cloudflare.svg" },
            { name: "Bash / Zsh", level: "Expert", note: "Scripting, dotfiles", icon: "/icons/shell-light.svg" },
        ],
    },

    {
        id: "languages",
        label: "Languages",
        color: "text-secondary",
        borderColor: "border-secondary/30",
        bgColor: "bg-secondary/10",
        progressColor: "bg-secondary",
        techs: [
            { name: "Python", level: "Expert", note: "Scripting, automation", icon: "/icons/python.svg" },
            { name: "Java", level: "Familiar", note: "OOP, Android basics", icon: "/icons/java.svg" },
            { name: "C++", level: "Familiar", note: "Performance, systems", icon: "/icons/cpp.svg" },
        ],
    },
];

export const TOOLS = [
    { name: "Neovim", tag: "editor", color: "text-accent", icon: "/icons/neovim.svg" },
    { name: "VSCode", tag: "editor", color: "text-primary", icon: "/icons/vscode.svg" },
    { name: "Figma", tag: "ui/ux design", color: "text-primary", icon: "/icons/figma.svg" },
    { name: "Adobe Photoshop", tag: "photo editing", color: "text-accent", icon: "/icons/adobe-photoshop.svg" },
    { name: "Adobe Illustrator", tag: "vector design", color: "text-secondary", icon: "/icons/adobe-illustrator.svg" },
    { name: "Adobe Premiere Pro", tag: "video editing", color: "text-accent", icon: "/icons/adobe-premiere-pro.svg" },
    { name: "Excalidraw", tag: "collaboration", color: "text-primary", icon: "/icons/excalidraw.svg" },
    { name: "Aseprite", tag: "pixel art", color: "text-primary", icon: "/icons/aseprite.svg" },
    { name: "Adobe", tag: "creative suite", color: "text-accent", icon: "/icons/adobe.svg" },
    { name: "GitHub", tag: "vcs", color: "text-foreground", icon: "/icons/github.svg", iconClassName: "invert" },
    { name: "Postman", tag: "api testing", color: "text-accent", icon: "/icons/postman.svg" },
    { name: "Neon.tech", tag: "database", color: "text-secondary", icon: "/icons/neon-tech.svg" },
    { name: "Obsidian", tag: "notes", color: "text-secondary", icon: "/icons/obsidian.svg" },
    { name: "Notion", tag: "notes", color: "text-accent", icon: "/icons/notion-light.svg" },
];

export const CURRENTLY_LEARNING = [
    { name: "Machine Learning", tag: "ai & data", color: "text-accent", context: "Exploring model training, data pipelines, and practical AI integration for web apps." },
];

export const WANT_TO_LEARN = [
    { name: "Rust", tag: "systems programming", color: "text-secondary", icon: "/icons/rust.svg", iconClassName: "invert" },
    { name: "Blender", tag: "3d modeling", color: "text-primary", icon: "/icons/blender.svg" },
    { name: "Godot", tag: "game engine", color: "text-accent", icon: "/icons/godot.svg" },
    { name: "Golang", tag: "backend", color: "text-secondary", icon: "/icons/golang.svg" },
    { name: "Raspberry Pi", tag: "iot / hardware", color: "text-primary", icon: "/icons/raspberry-pi.svg" },
    { name: "Electron", tag: "desktop apps", color: "text-accent", icon: "/icons/electron.svg" },
];

export const GRAPHICS_DESIGNS = [
    {
        id: "steam-showcase-full",
        type: "video" as const,
        src: "/images/graphics/showcase1.mp4",
        title: "Steam Profile Showcase",
        description: "Full animated showcase cover",
        height: 750,
    },
    {
        id: "steam-profile",
        type: "image" as const,
        src: "/images/graphics/steam-profile-showcase.png",
        title: "Steam Profile Layout",
        description: "Complete profile with custom showcase",
        height: 350,
        children: [
            {
                id: "steam-showcase-part1",
                type: "image" as const,
                src: "/images/graphics/steam-showcase-1.png",
                title: "Steam Showcase - Part 1",
                description: "Main character artwork",
                height: 550,
            },
            {
                id: "steam-showcase-part2",
                type: "image" as const,
                src: "/images/graphics/steam-showcase-2.png",
                title: "Steam Showcase - Part 2",
                description: "Extended artwork panel",
                height: 550,
            },
        ],
    },
    {
        id: "t-shirt-design",
        type: "image" as const,
        src: "/images/graphics/first-t-shirt-design.png",
        title: "T-Shirt Design",
        description: "Front & back polo shirt design",
        height: 350,
    },
    {
        id: "mc-gui-design",
        type: "image" as const,
        src: "/images/graphics/mc-gui0.png",
        title: "Minecraft GUI Design",
        description: "Custom server interface and HUD elements",
        height: 450,
        children: [
            {
                id: "mc-gui-main-menu",
                type: "image" as const,
                src: "/images/graphics/mc-gui1.png",
                title: "Main Menu GUI",
                description: "Custom pause/menu screen",
                height: 450,
            },
            {
                id: "mc-gui-inventory",
                type: "image" as const,
                src: "/images/graphics/mc-gui2.png",
                title: "Inventory GUI",
                description: "Custom inventory/skill layout",
                height: 500,
            },
            {
                id: "mc-gui-party",
                type: "image" as const,
                src: "/images/graphics/mc-party.png",
                title: "Party HUD",
                description: "MMORPG-style party interface",
                height: 350,
            },
            {
                id: "mc-gui-tags",
                type: "image" as const,
                src: "/images/graphics/mc-tag.png",
                title: "Role Tags",
                description: "Custom server rank tags",
                height: 550,
            },
        ],
    },
] as const;

export const PROJECTS = [
    {
        title: "Mindful Companion",
        desc: "AI mental health chatbot with self-help tools, mood tracking, and guided interventions. Designed to feel calm and trustworthy — not clinical.",
        period: "2026",
        cover: "/images/projects/mindful-cover.jpg",
        logo: "/images/projects/mindful-logo.webp",
        dot: "bg-[#1D9E75]",
        fallbackIcon: "🧠",
        techs: ["Next.js", "PostgreSQL", "Drizzle ORM", "Supabase"],
        liveUrl: "https://mindful-companion-gamma.vercel.app",
        githubUrl: null,
    },
    {
        title: "Minstrel Website",
        desc: "Library of songs collected from Discord, featuring search and playback with a custom-built audio player. Pairs with the Minstrel Bot to form a full pipeline.",
        period: "2026",
        cover: placeholderCover,
        logo: placeholderLogo,
        dot: "bg-[#BA7517]",
        fallbackIcon: "🎵",
        techs: ["React", "Tailwind CSS", "TanStack", "Drizzle ORM", "Neon DB"],
        liveUrl: "https://minstel-web-cnq.vercel.app/",
        githubUrl: "https://github.com/ABritex/minstel-web-cnq",
    },
    {
        title: "Minstrel Bot",
        desc: "Discord bot that collects, organizes, and serves songs from Discord servers directly into the Minstrel website — the data backbone of the whole system.",
        period: "2026",
        cover: placeholderCover,
        logo: placeholderLogo,
        dot: "bg-[#7F77DD]",
        fallbackIcon: "🤖",
        techs: ["TypeScript", "Discord.js", "Drizzle ORM", "Neon DB"],
        liveUrl: null,
        githubUrl: "https://github.com/ABritex/minstrel-bot",
    },
    {
        title: "JNDM Sari-Sari Store (Web)",
        desc: "Full-featured convenience store management web app for clients to manage inventory, sales, and analytics.",
        period: "2025",
        cover: placeholderCover,
        logo: "/images/projects/jndm-logo.webp",
        dot: "bg-[#4F46E5]",
        fallbackIcon: "🛒",
        techs: ["Next.js", "Firebase", "Tailwind CSS"],
        liveUrl: null,
        githubUrl: null,
        status: "postponed",
    },
    {
        title: "JNDM Sari-Sari Store (Mobile)",
        desc: "Tablet-based cashier app for sari-sari stores. Streamlines transactions, inventory tracking, and customer management.",
        period: "2025",
        cover: placeholderCover,
        logo: "/images/projects/jndm-logo.webp",
        dot: "bg-[#059669]",
        fallbackIcon: "📱",
        techs: ["Flutter", "Firebase", "Provider"],
        liveUrl: null,
        githubUrl: null,
        status: "postponed",
    },
    {
        title: "The Empire (Web)",
        desc: "Multi-purpose business management platform for food court, restaurant, PC cafe, and boarding room operations.",
        period: "2024",
        cover: placeholderCover,
        logo: "/images/projects/empire-logo.png",
        dot: "bg-[#DC2626]",
        fallbackIcon: "🏢",
        techs: ["Next.js", "Firebase", "TypeScript"],
        liveUrl: null,
        githubUrl: null,
        status: "postponed",
    },
    {
        title: "The Empire (Mobile)",
        desc: "Android-only staff app for The Empire building operations. Enables staff to manage orders, track bookings, and handle day-to-day operations.",
        period: "2024",
        cover: placeholderCover,
        logo: "/images/projects/empire-logo.png",
        dot: "bg-[#7C3AED]",
        fallbackIcon: "📱",
        techs: ["Android Studio", "Jetpack Compose", "Firebase"],
        liveUrl: null,
        githubUrl: null,
    }
];
