/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShowCaseRouteImport } from './routes/show-case'
import { Route as ContactMeRouteImport } from './routes/contact-me'
import { Route as IndexRouteImport } from './routes/index'

const ShowCaseRoute = ShowCaseRouteImport.update({
  id: '/show-case',
  path: '/show-case',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactMeRoute = ContactMeRouteImport.update({
  id: '/contact-me',
  path: '/contact-me',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact-me': typeof ContactMeRoute
  '/show-case': typeof ShowCaseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact-me': typeof ContactMeRoute
  '/show-case': typeof ShowCaseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact-me': typeof ContactMeRoute
  '/show-case': typeof ShowCaseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact-me' | '/show-case'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact-me' | '/show-case'
  id: '__root__' | '/' | '/contact-me' | '/show-case'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactMeRoute: typeof ContactMeRoute
  ShowCaseRoute: typeof ShowCaseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/show-case': {
      id: '/show-case'
      path: '/show-case'
      fullPath: '/show-case'
      preLoaderRoute: typeof ShowCaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-me': {
      id: '/contact-me'
      path: '/contact-me'
      fullPath: '/contact-me'
      preLoaderRoute: typeof ContactMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactMeRoute: ContactMeRoute,
  ShowCaseRoute: ShowCaseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
